# Numpy Tutorial

In [215]:
import numpy as np

In [216]:
array = np.array([[1,2,3,4,5]], np.int8)

In [217]:
print('prints array:',array)

prints array: [[1 2 3 4 5]]


In [218]:
print('Gives shape of array:',array.shape)

Gives shape of array: (1, 5)


In [219]:
print('Gives datatype of array:',array.dtype)

Gives datatype of array: int8


In [220]:
print('changed the element at(0,1)th position:')
array [0,1] = 45 
print(array)

changed the element at(0,1)th position:
[[ 1 45  3  4  5]]


In [221]:
array.size

5

In [222]:
print('array which have datatype as object')
np.array({1,2,3})

array which have datatype as object


array({1, 2, 3}, dtype=object)

In [223]:
zeros = np.zeros((2,5))
print("Created array with 0's filled in it:\n",zeros)

Created array with 0's filled in it:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [224]:
print('Array which consist total range of number:')
np.arange(15)

Array which consist total range of number:


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [225]:
print('Creates an array where from start to end numbers are divided into respecitve equal parts:')
# (initial num, final num, number of equal partitions)
linspace = np.linspace(1,10,12)
linspace

Creates an array where from start to end numbers are divided into respecitve equal parts:


array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [226]:
emp = np.empty(5)
print(emp)

[0.0e+000 9.9e-324 2.0e-323 4.9e-324 1.5e-323]


In [227]:
print('Creates an empty array which has same shape and size as of linspace:')
empty_like = np.empty_like(linspace)
empty_like

Creates an empty array which has same shape and size as of linspace:


array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [228]:
print('Identity matrix:')
identity_matrix = np.identity(5)
identity_matrix

Identity matrix:


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Reshape & Ravel

In [229]:
r_array = np.arange(100)
print('Normal Array:\n',r_array)
print('Shape:', r_array.shape)

reshape = r_array.reshape(5,20)
print('Reshape Array (reshapes in given shape if possible):\n',reshape)
print('Shape:', reshape.shape)

ravel = r_array.ravel()
print('Ravel array (converts back into one shaped array):\n', ravel)
print('Shape:', ravel.shape)

Normal Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Shape: (100,)
Reshape Array (reshapes in given shape if possible):
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
Shape: (5, 20)
Ravel array (converts back into one shaped array):
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74

### Axis

In [230]:
'''1D array have only 1 axis -> axis[0]
   2D array have 2 axis -> axis[0], axis[1]
   similarly for others
   
   whereas axis[0] is columnwise axis[1] is rowwise in 2D array'''

axis_array = [[1,2,6],[4,9,6],[3,8,9]]
arr = np.array(axis_array)
print(arr)
arr.sum(axis=0)

[[1 2 6]
 [4 9 6]
 [3 8 9]]


array([ 8, 19, 21])

In [247]:
print('Transpose of an array:\n', arr.T)

Transpose of an array:
 [[1 4 3]
 [2 9 8]
 [6 6 9]]


### Array iteration

In [232]:
# .flat is used for iteration

for i in arr.flat:
    print(i)

1
2
6
4
9
6
3
8
9


In [233]:
# .ndim to get the dimensions of an array

print('Diemsions of an array:', arr.ndim)

Diemsions of an array: 2


### Total bytes taken by array

In [234]:
print('Total nunber of bytes taken by arr:',arr.nbytes)

Total nunber of bytes taken by arr: 36


### Playing with args

In [235]:
one_d_array = np.array([1,5,2,64,2])
one_d_array

array([ 1,  5,  2, 64,  2])

In [236]:
print('smallest number on index:',one_d_array.argmin())
print('largest number on index:',one_d_array.argmax())
print('sorted array indexes:',one_d_array.argsort())

smallest number on index: 0
largest number on index: 3
sorted array indexes: [0 2 4 1 3]


In [237]:
# similarly for 2D array
print(arr)

print('smallest number on index:',arr.argmin())
print('smallest number on index for axis:',arr.argmin(axis=0))
print('largest number on index:',arr.argmax())
print('largest number on index for axis:',arr.argmax(axis=1))
print('sorted array indexes:\n',arr.argsort())
print('sorted array indexes:\n',arr.argsort(axis=1))

[[1 2 6]
 [4 9 6]
 [3 8 9]]
smallest number on index: 0
smallest number on index for axis: [0 0 0]
largest number on index: 4
largest number on index for axis: [2 1 2]
sorted array indexes:
 [[0 1 2]
 [0 2 1]
 [0 1 2]]
sorted array indexes:
 [[0 1 2]
 [0 2 1]
 [0 1 2]]


### array operations

In [238]:
arr1 = np.array([[1,2,3],[2,5,4],[3,0,1]])
arr2 = np.array([[3,2,5],[2,1,1],[3,1,2]])
print('arr1:\n',arr1)
print('arr2:\n',arr2)
print('addition:\n',arr1 + arr2)
print('difference:\n',arr1 - arr2)
print('multiplication:\n',arr1 * arr2)
print('divison:\n',arr1 / arr2)


arr1:
 [[1 2 3]
 [2 5 4]
 [3 0 1]]
arr2:
 [[3 2 5]
 [2 1 1]
 [3 1 2]]
addition:
 [[4 4 8]
 [4 6 5]
 [6 1 3]]
difference:
 [[-2  0 -2]
 [ 0  4  3]
 [ 0 -1 -1]]
multiplication:
 [[ 3  4 15]
 [ 4  5  4]
 [ 9  0  2]]
divison:
 [[0.33333333 1.         0.6       ]
 [1.         5.         4.        ]
 [1.         0.         0.5       ]]


In [239]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 2.23606798, 2.        ],
       [1.73205081, 0.        , 1.        ]])

In [240]:
print('arr1:\n', arr1)
print(np.max(arr1))
print(np.min(arr1))

# condition checking

np.where(arr1>3)

arr1:
 [[1 2 3]
 [2 5 4]
 [3 0 1]]
5
0


(array([1, 1], dtype=int64), array([1, 2], dtype=int64))

In [241]:
np.count_nonzero(arr1)

8

In [242]:
np.nonzero(arr1)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 2], dtype=int64))

In [244]:
import sys
a = [1,2,3,4,5]
b = np.array([1,2,3,4,5])
print('size of python array:',sys.getsizeof(1)*len(a))
print('size of numpy array:',b.nbytes)

size of python array: 140
size of numpy array: 20
