# Numpy Tutorial

In [2]:
import numpy as np

In [20]:
array = np.array([[1,2,3,4,5]], np.int8)

In [17]:
print('prints array:',array)

prints array: [[1 2 3 4 5]
 [2 3 4 5 6]]


In [21]:
print('Gives shape of array:',array.shape)

Gives shape of array: (1, 5)


In [6]:
print('Gives datatype of array:',array.dtype)

Gives datatype of array: int8


In [7]:
print('changed the element at(0,1)th position:')
array [0,1] = 45 

changed the element at(0,1)th position:


In [8]:
array

array([[ 1, 45,  3,  4,  5]], dtype=int8)

In [9]:
array.size

5

In [10]:
print('array which have datatype as object')
np.array({1,2,3})

array which have datatype as object


array({1, 2, 3}, dtype=object)

In [11]:
zeros = np.zeros((2,5))
print("Created array with 0's filled in it:\n",zeros)

Created array with 0's filled in it:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
print('Array which consist total range of number:')
np.arange(15)

Array which consist total range of number:


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
print('Creates an array where from start to end numbers are divided into respecitve equal parts:')
# (initial num, final num, number of equal partitions)
np.linspace(1,10,12)

Creates an array where from start to end numbers are divided into respecitve equal parts:


array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [14]:
emp = np.empty(5)
print(emp)

[0.00000000e+000 8.40905506e-312 8.40905506e-312 8.40905506e-312
 0.00000000e+000]
